/**
 * Shared publish logic:
 * - Marks a song or video as "published"
 * - Finds all followers of the artist and sends them a new_release notification
 * - Used by the submission approval flow and the scheduled auto-publisher
 */
import { eq, and, lte, inArray } from "drizzle-orm";
import {
  db, songsTable, videosTable, submissionsTable,
  artistsTable, followsTable, usersTable, eventsTable,
} from "@workspace/db";
import { logger } from "./logger";
import { notify } from "./notify";
import { getTodayInReleaseTimezone } from "./timezone";

/**
 * True when a releaseDate ("YYYY-MM-DD" or null) has not arrived yet.
 * A null/empty releaseDate means "no schedule" — never treated as future.
 * Compared against "today" in US Eastern Time (see timezone.ts), not server/DB UTC.
 */
export function isFutureRelease(releaseDate: string | null | undefined): boolean {
  if (!releaseDate) return false;
  const today = getTodayInReleaseTimezone();
  return releaseDate > today;
}

/**
 * Publishes a song or video, but refuses to do so early: if the content's own
 * releaseDate hasn't arrived yet, this is a no-op (the scheduled-release job
 * will publish it once the date arrives). This is the single choke point for
 * publishing, so no call site — direct admin action, legacy submission PATCH,
 * or the scheduler itself — can push content live ahead of its release date.
 */
export async function publishContent(
  type: "song" | "video",
  contentId: number,
  opts: { submissionId?: number } = {}
): Promise<{ published: boolean; releaseDate: string | null }> {
  const table = type === "song" ? songsTable : videosTable;
  const [row] = await db
    .select({ releaseDate: table.releaseDate })
    .from(table)
    .where(eq(table.id, contentId))
    .limit(1);
  const releaseDate = row?.releaseDate ?? null;

  if (isFutureRelease(releaseDate)) {
    // Make sure it's at least marked "approved" so the scheduler will pick it up.
    await db.update(table).set({ status: "approved" }).where(eq(table.id, contentId));
    logger.warn({ type, contentId, releaseDate }, "publishContent blocked: release date has not arrived yet");
    return { published: false, releaseDate };
  }

  if (type === "song") {
    await db.update(songsTable).set({ status: "published" }).where(eq(songsTable.id, contentId));
    await sendFollowerNotifications("song", contentId, opts.submissionId);
    if (opts.submissionId) {
      await db.update(submissionsTable).set({ status: "published" }).where(eq(submissionsTable.id, opts.submissionId));
    }
  } else {
    await db.update(videosTable).set({ status: "published" }).where(eq(videosTable.id, contentId));
    await sendFollowerNotifications("video", contentId, opts.submissionId);
    if (opts.submissionId) {
      await db.update(submissionsTable).set({ status: "published" }).where(eq(submissionsTable.id, opts.submissionId));
    }
  }
  await createReleaseEvent(type, contentId);
  return { published: true, releaseDate };
}

async function createReleaseEvent(type: "song" | "video", contentId: number) {
  try {
    let artistId: number | null = null;
    let title = "";
    let releaseDate: string | null = null;

    if (type === "song") {
      const [song] = await db
        .select({ artistId: songsTable.artistId, title: songsTable.title, releaseDate: songsTable.releaseDate })
        .from(songsTable).where(eq(songsTable.id, contentId)).limit(1);
      if (!song) return;
      artistId = song.artistId;
      title = song.title;
      releaseDate = song.releaseDate;
    } else {
      const [video] = await db
        .select({ artistId: videosTable.artistId, title: videosTable.title, releaseDate: videosTable.releaseDate })
        .from(videosTable).where(eq(videosTable.id, contentId)).limit(1);
      if (!video) return;
      artistId = video.artistId;
      title = video.title;
      releaseDate = video.releaseDate;
    }

    const [artist] = await db
      .select({ userId: artistsTable.userId })
      .from(artistsTable).where(eq(artistsTable.id, artistId)).limit(1);
    if (!artist?.userId) return;

    await db.insert(eventsTable).values({
      userId: artist.userId,
      title: `New ${type === "song" ? "song" : "video"} release: ${title}`,
      type: "release",
      eventDate: releaseDate ?? getTodayInReleaseTimezone(),
      isAutoGenerated: true,
    });
  } catch (err) {
    logger.error({ err, type, contentId }, "Failed to create auto-generated release event");
  }
}

async function sendFollowerNotifications(
  type: "song" | "video",
  contentId: number,
  submissionId?: number
) {
  // Get content details + artist
  let artistId: number | null = null;
  let contentTitle = "";
  let artistName = "";
  let coverUrl: string | null = null;

  if (type === "song") {
    const [song] = await db
      .select({ artistId: songsTable.artistId, title: songsTable.title, coverUrl: songsTable.coverUrl })
      .from(songsTable).where(eq(songsTable.id, contentId)).limit(1);
    if (!song) return;
    artistId = song.artistId;
    contentTitle = song.title;
    coverUrl = song.coverUrl;
  } else {
    const [video] = await db
      .select({ artistId: videosTable.artistId, title: videosTable.title, thumbnailUrl: videosTable.thumbnailUrl })
      .from(videosTable).where(eq(videosTable.id, contentId)).limit(1);
    if (!video) return;
    artistId = video.artistId;
    contentTitle = video.title;
    coverUrl = video.thumbnailUrl;
  }

  const [artist] = await db
    .select({ stageName: artistsTable.stageName })
    .from(artistsTable).where(eq(artistsTable.id, artistId)).limit(1);
  artistName = artist?.stageName ?? "Unknown Artist";

  // Get all followers of this artist
  const followers = await db
    .select({ followerId: followsTable.followerId })
    .from(followsTable)
    .where(and(eq(followsTable.targetType, "artist"), eq(followsTable.targetId, artistId)));

  if (!followers.length) return;

  const followerIds = followers.map((f) => f.followerId);

  const notifications = followerIds.map((userId) => ({
    userId,
    type: "new_release" as const,
    title: `${artistName} just dropped a new ${type}!`,
    message: `"${contentTitle}" is now available to ${type === "song" ? "stream" : "watch"}. Check it out!`,
    isRead: false,
    submissionId: submissionId ?? null,
  }));

  if (notifications.length) {
    await notify(notifications);
    logger.info({ artistId, contentId, type, followerCount: followers.length }, "Sent release notifications to followers");
  }
}

/**
 * Scheduled job: auto-publish approved songs/videos whose releaseDate has arrived.
 * Call once at startup — runs every 60 seconds.
 */
export function startReleaseScheduler() {
  const runCheck = async () => {
    try {
      const today = getTodayInReleaseTimezone(); // YYYY-MM-DD in US Eastern Time

      // Songs: approved, has a releaseDate <= today
      const readySongs = await db
        .select({ id: songsTable.id })
        .from(songsTable)
        .where(and(
          eq(songsTable.status, "approved"),
          lte(songsTable.releaseDate, today)
        ));

      for (const song of readySongs) {
        // Find the matching submission
        const [sub] = await db
          .select({ id: submissionsTable.id })
          .from(submissionsTable)
          .where(and(eq(submissionsTable.contentId, song.id), eq(submissionsTable.type, "song")))
          .limit(1);
        await publishContent("song", song.id, { submissionId: sub?.id });
        logger.info({ songId: song.id }, "Scheduled release: song published");
      }

      // Videos: approved, has a releaseDate <= today
      const readyVideos = await db
        .select({ id: videosTable.id })
        .from(videosTable)
        .where(and(
          eq(videosTable.status, "approved"),
          lte(videosTable.releaseDate, today)
        ));

      for (const video of readyVideos) {
        const [sub] = await db
          .select({ id: submissionsTable.id })
          .from(submissionsTable)
          .where(and(eq(submissionsTable.contentId, video.id), eq(submissionsTable.type, "video")))
          .limit(1);
        await publishContent("video", video.id, { submissionId: sub?.id });
        logger.info({ videoId: video.id }, "Scheduled release: video published");
      }
    } catch (err) {
      logger.error({ err }, "Release scheduler error");
    }
  };

  // Run immediately on startup, then every 60 seconds
  runCheck();
  setInterval(runCheck, 60_000);
}
