import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import songsRouter from "./songs";
import videosRouter from "./videos";
import artistsRouter from "./artists";
import labelsRouter from "./labels";
import playlistsRouter from "./playlists";
import commentsRouter from "./comments";
import favoritesRouter from "./favorites";
import submissionsRouter from "./submissions";
import libraryRouter from "./library";
import homeRouter from "./home";
import discoverRouter from "./discover";
import companyRouter from "./company";
import adminRouter from "./admin";
import paymentsRouter from "./payments";
import chatRouter from "./chat";
import notificationsRouter from "./notifications";
import storageRouter from "./storage";
import analyticsRouter from "./analytics";
import artistAnalyticsRouter from "./artist-analytics";
import labelAnalyticsRouter from "./label-analytics";
import editorialPlaylistsRouter from "./editorial-playlists";
import editorPicksRouter from "./editor-picks";
import messagesRouter from "./messages";
import legalRouter from "./legal";
import blocksRouter from "./blocks";
import safetyRouter from "./safety";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(songsRouter);
router.use(videosRouter);
router.use(artistsRouter);
router.use(labelsRouter);
router.use(playlistsRouter);
router.use(commentsRouter);
router.use(favoritesRouter);
router.use(submissionsRouter);
router.use(libraryRouter);
router.use(homeRouter);
router.use(discoverRouter);
router.use(companyRouter);
router.use(adminRouter);
router.use(paymentsRouter);
router.use(chatRouter);
router.use(notificationsRouter);
router.use(storageRouter);
router.use(analyticsRouter);
router.use(artistAnalyticsRouter);
router.use(labelAnalyticsRouter);
router.use(editorialPlaylistsRouter);
router.use(editorPicksRouter);
router.use(messagesRouter);
router.use(legalRouter);
router.use(blocksRouter);
router.use(safetyRouter);

export default router;
