import { Link } from "wouter";
import { Brain, ChevronLeft, Shield, Lock, Eye, Rss, AlertTriangle, Scale } from "lucide-react";

export default function TrustAI() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="border-b border-border/50 bg-card/80 backdrop-blur sticky top-0 z-30">
        <div className="max-w-3xl mx-auto px-6 h-14 flex items-center gap-4">
          <Link href="/trust">
            <button className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors">
              <ChevronLeft className="w-4 h-4" />Trust Center
            </button>
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-12 pb-20 space-y-10">
        <div>
          <div className="flex items-center gap-3 mb-3">
            <div className="w-9 h-9 rounded-lg bg-violet-400/10 flex items-center justify-center">
              <Brain className="w-4.5 h-4.5 text-violet-400" />
            </div>
            <span className="text-xs text-muted-foreground uppercase tracking-wider font-semibold">AI & Technology</span>
          </div>
          <h1 className="text-3xl font-extrabold tracking-tight mb-3">AI & Technology</h1>
          <p className="text-muted-foreground leading-relaxed">
            Everyday Radio takes a careful, creator-first approach to AI and platform technology.
            This section explains how we currently handle AI, data, and platform protection.
          </p>
        </div>

        <div className="space-y-6">
          <div className="p-6 rounded-xl bg-card border border-border space-y-3">
            <div className="flex items-center gap-2">
              <Brain className="w-4 h-4 text-violet-400" />
              <h2 className="font-semibold">AI Usage Statement</h2>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Everyday Radio does not currently use creator content to train AI systems. Your uploaded
              music, videos, or creative work is not fed into AI training pipelines.
            </p>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Any meaningful future change to our AI practices will be disclosed through the
              AI Policy and the AI Change Log before it takes effect.
            </p>
            <Link href="/legal/ai-policy">
              <button className="mt-2 text-sm text-primary font-semibold hover:underline">Read the full AI Content Policy →</button>
            </Link>
          </div>

          <div className="p-6 rounded-xl bg-card border border-border space-y-3">
            <div className="flex items-center gap-2">
              <Scale className="w-4 h-4 text-violet-400" />
              <h2 className="font-semibold">Platform Stance on AI Content</h2>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Everyday Radio welcomes human-created, AI-assisted, and hybrid creative work. However, we currently do not accept content that is fully generated by artificial intelligence without meaningful human creative authorship.
            </p>
            <p className="text-sm text-muted-foreground leading-relaxed">
              This means content where no human played a meaningful creative role — selecting, guiding, editing, or significantly shaping the result — is not eligible for publication on the platform at this time.
            </p>
            <Link href="/legal/ai-policy">
              <button className="mt-2 text-sm text-primary font-semibold hover:underline">AI Content Policy (Section 12) →</button>
            </Link>
          </div>

          <div className="p-6 rounded-xl bg-card border border-border space-y-3">
            <div className="flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 text-amber-400" />
              <h2 className="font-semibold">AI Detection Tool Advisory</h2>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Our team may use automated AI detection tools to supplement creator disclosures and flag content that may not comply with platform policy. These tools provide a signal — not a verdict.
            </p>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Automated detection is imperfect. AI detection scores can produce false positives, especially for content that uses software instruments, sample libraries, or digital production techniques that were not created with AI but share characteristics that detection models associate with AI generation.
            </p>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Detection results are one input in a human-led review process. No content is permanently classified or removed based solely on an automated score. If you believe a classification applied to your content is incorrect, you have the right to dispute it.
            </p>
          </div>

          <div className="p-6 rounded-xl bg-card border border-border space-y-3">
            <div className="flex items-center gap-2">
              <Brain className="w-4 h-4 text-violet-400" />
              <h2 className="font-semibold">AI Content Origin Tagging</h2>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Everyday Radio uses a transparent content origin tagging system so listeners always know whether tracks and videos are human-created, AI-assisted, hybrid, or (where permitted) fully AI-generated.
            </p>
            <div className="space-y-2">
              {[
                { label: "Human Created", desc: "Minimal or no AI involvement — written, performed, and produced by human artists." },
                { label: "AI Assisted", desc: "AI tools were used in part of the creative process (mixing, mastering assistance, lyric suggestions) but the core creative work is human." },
                { label: "Human + AI Collaboration", desc: "Meaningful human and AI contributions are both present throughout the work." },
                { label: "Fully AI Generated", desc: "Content generated entirely by AI with no meaningful human creative authorship. Not accepted under current platform policy." },
              ].map(({ label, desc }) => (
                <div key={label} className="rounded-lg bg-secondary/30 px-4 py-3 space-y-0.5">
                  <p className="text-sm font-medium">{label}</p>
                  <p className="text-xs text-muted-foreground">{desc}</p>
                </div>
              ))}
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Origin tags are set by creators at submission time and may be supplemented by automated detection scans. Platform staff may adjust or lock tags after review.
            </p>
          </div>

          <div className="p-6 rounded-xl bg-card border border-border space-y-3">
            <div className="flex items-center gap-2">
              <Scale className="w-4 h-4 text-green-400" />
              <h2 className="font-semibold">Creator Appeal Rights</h2>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Creators have the right to dispute any AI authorship tag or platform decision they believe is incorrect. You do not need to accept a classification you disagree with.
            </p>
            <p className="text-sm text-muted-foreground leading-relaxed">
              To dispute a tag, submit an AI authorship tag dispute through the Appeals process. Your appeal will be reviewed by a member of the platform team. If the appeal is upheld, the tag will be corrected and the content will remain published without interruption. If additional information is needed, we may contact you at the email address on your account.
            </p>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Appeals are typically reviewed within a few business days. Submitting an appeal pauses any enforcement action tied to a classification while your case is under review.
            </p>
            <Link href="/trust/appeals">
              <button className="mt-2 text-sm text-primary font-semibold hover:underline">Submit an AI Authorship Tag Dispute →</button>
            </Link>
          </div>

          <div className="p-6 rounded-xl bg-card border border-border space-y-3">
            <div className="flex items-center gap-2">
              <Shield className="w-4 h-4 text-green-400" />
              <h2 className="font-semibold">Scraping & Bot Protection</h2>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Everyday Radio actively protects creator content and platform data from automated
              harvesting. These defenses are always on — not temporary.
            </p>
            <ul className="text-sm text-muted-foreground space-y-1.5 pl-1">
              <li className="flex items-start gap-2"><span className="text-green-400 mt-0.5">✓</span><span><strong className="text-foreground">Authentication gate</strong> — all catalog endpoints (songs, videos, artists, labels) require a valid account. Unauthenticated requests receive 401.</span></li>
              <li className="flex items-start gap-2"><span className="text-green-400 mt-0.5">✓</span><span><strong className="text-foreground">Bot detection</strong> — automated clients (scrapers, crawlers, headless HTTP libraries) are identified and blocked before any data is returned.</span></li>
              <li className="flex items-start gap-2"><span className="text-green-400 mt-0.5">✓</span><span><strong className="text-foreground">Rate limiting</strong> — all API endpoints enforce per-IP request limits. Sustained automated traffic is throttled and blocked.</span></li>
              <li className="flex items-start gap-2"><span className="text-green-400 mt-0.5">✓</span><span><strong className="text-foreground">Brute-force protection</strong> — login, registration, and password-reset endpoints have a stricter limit to prevent credential attacks.</span></li>
              <li className="flex items-start gap-2"><span className="text-green-400 mt-0.5">✓</span><span><strong className="text-foreground">robots.txt</strong> — the <code className="text-xs bg-muted px-1 py-0.5 rounded">/api/</code> path and all content paths are disallowed for web crawlers.</span></li>
            </ul>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Scraping Everyday Radio is a violation of our{" "}
              <Link href="/legal/terms">
                <span className="text-primary hover:underline cursor-pointer">Terms of Service</span>
              </Link>
              {" "}(Section 13). Unauthorized automated access may result in permanent blocking and legal action.
            </p>
          </div>

          <div className="p-6 rounded-xl bg-card border border-border space-y-3">
            <div className="flex items-center gap-2">
              <Lock className="w-4 h-4 text-orange-400" />
              <h2 className="font-semibold">Data Protection</h2>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Personal data is collected only as needed to provide the platform. We do not sell
              personal data to third parties. See our Privacy Policy for the complete picture.
            </p>
            <Link href="/legal/privacy">
              <button className="mt-2 text-sm text-primary font-semibold hover:underline">Read the Privacy Policy →</button>
            </Link>
          </div>

          <div className="p-6 rounded-xl bg-card border border-border space-y-3">
            <div className="flex items-center gap-2">
              <Eye className="w-4 h-4 text-cyan-400" />
              <h2 className="font-semibold">Platform Security</h2>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed">
              We use industry-standard security practices including encrypted connections, secure token
              authentication, and password hashing. We do not expose private security architecture
              or internal vulnerability details.
            </p>
            <Link href="/trust/security">
              <button className="mt-2 text-sm text-primary font-semibold hover:underline">Security & Privacy →</button>
            </Link>
          </div>

          <div className="p-6 rounded-xl bg-card border border-border space-y-3">
            <div className="flex items-center gap-2">
              <Rss className="w-4 h-4 text-yellow-400" />
              <h2 className="font-semibold">Future AI Change Log</h2>
              <span className="text-[10px] bg-amber-500/15 text-amber-400 border border-amber-500/30 px-2 py-0.5 rounded font-semibold uppercase tracking-wide">Planned</span>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Any meaningful future changes to how we use AI will be logged here for full
              transparency. This log is currently empty — no AI practice changes have occurred since launch.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
